name: Check

on: [push, pull_request]

jobs:
  build_and_test:
    name: Check Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.83.0
          target: aarch64-unknown-linux-gnu
      - name: Build
        run: cargo build --release
      - name: check publish
        run: cargo publish --dry-run
